# Generated by Django 4.2.1 on 2023-08-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
